### PR TITLE
Allow setting environment name and debug mode from borisrc

### PR DESCRIPTION
**Pull request by philrennie**
Small addition to let you specify the environment name and debug mode from ./borisrc

I often use dev environments other then dev. Adding some system environment variables into the mix you can reconfigure the boris loader on the fly

export BORIS_SYMFONY_ENV=wacky_env_name
export BORIS_SYMFONY_DEBUG=false

~/.borisrc
<?php
require '/Users/phil/boris-loader/boris-loader.php';

// false if not found in ENV
$env = getenv('BORIS_SYMFONY_ENV'); 
$debug = getenv('BORIS_SYMFONY_DEBUG');

// Use found value or defaults
$env = $env ? $env : 'dev'; 
$debug = $debug ? $debug : true;

\Boris\Loader\Loader::load($boris, [ new \Boris\Loader\Provider\Symfony2($env, $debug),]);

### CODE REVIEW

**Comment by tobiassjosten** [comment]
I like it! Thanks for sharing. :)

Two things though:
- Could you document this in `REAME.md`? Maybe add a short Symfony provider specific section after *Providers*?
- I'm guessing it should be `$this->debug` instead of just `$debug` at [line 39](https://github.com/philrennie/boris-loader/blob/57173b4bbfd391e417ad7d6a83b0adc62709fa72/src/Boris/Loader/Provider/Symfony2.php#L39)?

**Comment by philrennie** [comment]
Yeah can do, glad you think's it's useful. 

That definitely should be a $this->debug, cheers.

**Comment by philrennie** [comment]
Used the online tools for editing here for the first time. That was an exercise in creating many tiny commits :)
Added additional info to the README and put some stuff about using env vars in a separate file for tidiness.

**Comment by tobiassjosten** [comment]
Thanks for that!

**Pull request merged**
